/* ALTER TABLE `voters` 
ADD COLUMN connectioninfo TEXT CHARACTER SET utf8 COLLATE UTF8_BIN;
ALTER TABLE `voters` 
ADD COLUMN connection VARCHAR(1) CHARACTER SET utf8 COLLATE UTF8_BIN;
*/

UPDATE voters SET CONNECTION = 'N';
UPDATE voters SET CONNECTIONINFO = '';

update voters set connectioninfo = 'Known by: . How known:?? is this the woman on CB1 with Evie?' , connection = 'Y' where id = '301516662';
update voters set connectioninfo = 'Known by: .How known:Chatted him up during construction of building; seems very politically involved; not sure if hes got a horse in the race already.  Have heard some MAGA talk, from him, though' , connection = 'Y' where id = 'Q1360700';
update voters set connectioninfo = 'Known by: .How known:Hes no longer at this address. We live here now! ' , connection = 'Y' where id = '305132340';
update voters set connectioninfo = 'Known by: .How known:I recognize her name from AMAN' , connection = 'Y' where id = '410642903';
update voters set connectioninfo = 'Known by: .How known:Lives in Megans building but she doesnt know them' , connection = 'Y' where id = '305931740';
update voters set connectioninfo = 'Known by: .How known:Lives in Megans building I dont know her' , connection = 'Y' where id = '410913869';
update voters set connectioninfo = 'Known by: .How known:Lives in Megans building I dont know him and he may have moved' , connection = 'Y' where id = '411505026';
update voters set connectioninfo = 'Known by: .How known:Lives in Megans building, I know him a little' , connection = 'Y' where id = '305841422';
update voters set connectioninfo = 'Known by: .How known:Lives in Megans building, she is moderately politically active and we get on well' , connection = 'Y' where id = '302370150';
update voters set connectioninfo = 'Known by: .How known:Maryam lives in the building. I dont know folks here but can try to help organize. ' , connection = 'Y' where id = '300092056';
update voters set connectioninfo = 'Known by: .How known:Maryam lives in the building. I dont know folks here but can try to help organize. ' , connection = 'Y' where id = '300143137';
update voters set connectioninfo = 'Known by: .How known:Maryam lives in the building. I dont know folks here but can try to help organize. ' , connection = 'Y' where id = '301018344';
update voters set connectioninfo = 'Known by: .How known:Maryam lives in the building. I dont know folks here but can try to help organize. ' , connection = 'Y' where id = '301094003';
update voters set connectioninfo = 'Known by: .How known:Maryam lives in the building. I dont know folks here but can try to help organize. ' , connection = 'Y' where id = '301282754';
update voters set connectioninfo = 'Known by: .How known:Maryam lives in the building. I dont know folks here but can try to help organize. ' , connection = 'Y' where id = '301838909';
update voters set connectioninfo = 'Known by: .How known:Maryam lives in the building. I dont know folks here but can try to help organize. ' , connection = 'Y' where id = '301882515';
update voters set connectioninfo = 'Known by: .How known:Maryam lives in the building. I dont know folks here but can try to help organize. ' , connection = 'Y' where id = '302086252';
update voters set connectioninfo = 'Known by: .How known:Maryam lives in the building. I dont know folks here but can try to help organize. ' , connection = 'Y' where id = '302266375';
update voters set connectioninfo = 'Known by: .How known:Maryam lives in the building. I dont know folks here but can try to help organize. ' , connection = 'Y' where id = '302328962';
update voters set connectioninfo = 'Known by: .How known:Maryam lives in the building. I dont know folks here but can try to help organize. ' , connection = 'Y' where id = '302468307';
update voters set connectioninfo = 'Known by: .How known:Maryam lives in the building. I dont know folks here but can try to help organize. ' , connection = 'Y' where id = '302711498';
update voters set connectioninfo = 'Known by: .How known:Maryam lives in the building. I dont know folks here but can try to help organize. ' , connection = 'Y' where id = '302711506';
update voters set connectioninfo = 'Known by: .How known:Maryam lives in the building. I dont know folks here but can try to help organize. ' , connection = 'Y' where id = '302999445';
update voters set connectioninfo = 'Known by: .How known:Maryam lives in the building. I dont know folks here but can try to help organize. ' , connection = 'Y' where id = '303160576';
update voters set connectioninfo = 'Known by: .How known:Maryam lives in the building. I dont know folks here but can try to help organize. ' , connection = 'Y' where id = '303401598';
update voters set connectioninfo = 'Known by: .How known:Maryam lives in the building. I dont know folks here but can try to help organize. ' , connection = 'Y' where id = '303447903';
update voters set connectioninfo = 'Known by: .How known:Maryam lives in the building. I dont know folks here but can try to help organize. ' , connection = 'Y' where id = '303645986';
update voters set connectioninfo = 'Known by: .How known:Maryam lives in the building. I dont know folks here but can try to help organize. ' , connection = 'Y' where id = '303671746';
update voters set connectioninfo = 'Known by: .How known:Maryam lives in the building. I dont know folks here but can try to help organize. ' , connection = 'Y' where id = '303671753';
update voters set connectioninfo = 'Known by: .How known:Maryam lives in the building. I dont know folks here but can try to help organize. ' , connection = 'Y' where id = '303761982';
update voters set connectioninfo = 'Known by: .How known:Maryam lives in the building. I dont know folks here but can try to help organize. ' , connection = 'Y' where id = '303954114';
update voters set connectioninfo = 'Known by: .How known:Maryam lives in the building. I dont know folks here but can try to help organize. ' , connection = 'Y' where id = '303983153';
update voters set connectioninfo = 'Known by: .How known:Maryam lives in the building. I dont know folks here but can try to help organize. ' , connection = 'Y' where id = '304009823';
update voters set connectioninfo = 'Known by: .How known:Maryam lives in the building. I dont know folks here but can try to help organize. ' , connection = 'Y' where id = '304017101';
update voters set connectioninfo = 'Known by: .How known:Maryam lives in the building. I dont know folks here but can try to help organize. ' , connection = 'Y' where id = '304144114';
update voters set connectioninfo = 'Known by: .How known:Maryam lives in the building. I dont know folks here but can try to help organize. ' , connection = 'Y' where id = '304214674';
update voters set connectioninfo = 'Known by: .How known:Maryam lives in the building. I dont know folks here but can try to help organize. ' , connection = 'Y' where id = '304223326';
update voters set connectioninfo = 'Known by: .How known:Maryam lives in the building. I dont know folks here but can try to help organize. ' , connection = 'Y' where id = '304334447';
update voters set connectioninfo = 'Known by: .How known:Maryam lives in the building. I dont know folks here but can try to help organize. ' , connection = 'Y' where id = '304538842';
update voters set connectioninfo = 'Known by: .How known:Maryam lives in the building. I dont know folks here but can try to help organize. ' , connection = 'Y' where id = '304585736';
update voters set connectioninfo = 'Known by: .How known:Maryam lives in the building. I dont know folks here but can try to help organize. ' , connection = 'Y' where id = '304616590';
update voters set connectioninfo = 'Known by: .How known:Maryam lives in the building. I dont know folks here but can try to help organize. ' , connection = 'Y' where id = '304903254';
update voters set connectioninfo = 'Known by: .How known:Maryam lives in the building. I dont know folks here but can try to help organize. ' , connection = 'Y' where id = '305368294';
update voters set connectioninfo = 'Known by: .How known:Maryam lives in the building. I dont know folks here but can try to help organize. ' , connection = 'Y' where id = '305489854';
update voters set connectioninfo = 'Known by: .How known:Maryam lives in the building. I dont know folks here but can try to help organize. ' , connection = 'Y' where id = '305586949';
update voters set connectioninfo = 'Known by: .How known:Maryam lives in the building. I dont know folks here but can try to help organize. ' , connection = 'Y' where id = '305990285';
update voters set connectioninfo = 'Known by: .How known:Maryam lives in the building. I dont know folks here but can try to help organize. ' , connection = 'Y' where id = '306255250';
update voters set connectioninfo = 'Known by: .How known:Maryam lives in the building. I dont know folks here but can try to help organize. ' , connection = 'Y' where id = '410491098';
update voters set connectioninfo = 'Known by: .How known:Maryam lives in the building. I dont know folks here but can try to help organize. ' , connection = 'Y' where id = '410536486';
update voters set connectioninfo = 'Known by: .How known:Maryam lives in the building. I dont know folks here but can try to help organize. ' , connection = 'Y' where id = '410654248';
update voters set connectioninfo = 'Known by: .How known:Maryam lives in the building. I dont know folks here but can try to help organize. ' , connection = 'Y' where id = '410781554';
update voters set connectioninfo = 'Known by: .How known:Maryam lives in the building. I dont know folks here but can try to help organize. ' , connection = 'Y' where id = '410811802';
update voters set connectioninfo = 'Known by: .How known:Maryam lives in the building. I dont know folks here but can try to help organize. ' , connection = 'Y' where id = '410820616';
update voters set connectioninfo = 'Known by: .How known:Maryam lives in the building. I dont know folks here but can try to help organize. ' , connection = 'Y' where id = '411366052';
update voters set connectioninfo = 'Known by: .How known:Maryam lives in the building. I dont know folks here but can try to help organize. ' , connection = 'Y' where id = '411550038';
update voters set connectioninfo = 'Known by: .How known:Maryam lives in the building. I dont know folks here but can try to help organize. ' , connection = 'Y' where id = '411648000';
update voters set connectioninfo = 'Known by: .How known:Maryam lives in the building. I dont know folks here but can try to help organize. ' , connection = 'Y' where id = '412272563';
update voters set connectioninfo = 'Known by: .How known:Maryam lives in the building. I dont know folks here but can try to help organize. ' , connection = 'Y' where id = '412461938';
update voters set connectioninfo = 'Known by: .How known:Maryam lives in the building. I dont know folks here but can try to help organize. ' , connection = 'Y' where id = 'Q1369643';
update voters set connectioninfo = 'Known by: .How known:Megan - lives my apartment building. We dont get on, I get along very well with her sister, whos my next door neighbor.' , connection = 'Y' where id = '301699710';
update voters set connectioninfo = 'Known by: .How known:Megan knows herbut we arent close anymore; someone else would be better to reach out.' , connection = 'Y' where id = '412264734';
update voters set connectioninfo = 'Known by: .How known:Megan; were friendly, her son goes to PS17' , connection = 'Y' where id = '410088734';
update voters set connectioninfo = 'Known by: .How known:Megans friend but working for Caban' , connection = 'Y' where id = '412457052';
update voters set connectioninfo = 'Known by: .How known:Megans husband' , connection = 'Y' where id = '410645441';
update voters set connectioninfo = 'Known by: .How known:Might have moved' , connection = 'Y' where id = '304051834';
update voters set connectioninfo = 'Known by: .How known:Moved - lived in Megans building' , connection = 'Y' where id = '411181696';
update voters set connectioninfo = 'Known by: .How known:Pretty sure shes moved' , connection = 'Y' where id = '411154608';
update voters set connectioninfo = 'Known by: .How known:Self; just a wonderful person, perfect in pretty much every way' , connection = 'Y' where id = '410234396';
update voters set connectioninfo = 'Known by: .How known:Was Megans neighbor, but Sara moved; not sure of affiliation of new family in her apartment' , connection = 'Y' where id = '410392716';
update voters set connectioninfo = 'Known by: .How known:working on Evies campaign' , connection = 'Y' where id = '300541234';
update voters set connectioninfo = 'Known by: .How known:Maryam lives in the building. I dont know folks here but can try to help organize. ' , connection = 'Y' where id = '300701341';
update voters set connectioninfo = 'Known by: .How known:Maryam lives in the building. I dont know folks here but can try to help organize. ' , connection = 'Y' where id = '301313275';
update voters set connectioninfo = 'Known by: .How known:Maryam lives in the building. I dont know folks here but can try to help organize. ' , connection = 'Y' where id = '301827925';
update voters set connectioninfo = 'Known by: .How known:Maryam lives in the building. I dont know folks here but can try to help organize. ' , connection = 'Y' where id = '301855005';
update voters set connectioninfo = 'Known by: .How known:Maryam lives in the building. I dont know folks here but can try to help organize. ' , connection = 'Y' where id = '301956976';
update voters set connectioninfo = 'Known by: .How known:Maryam lives in the building. I dont know folks here but can try to help organize. ' , connection = 'Y' where id = '302950155';
update voters set connectioninfo = 'Known by: .How known:Maryam lives in the building. I dont know folks here but can try to help organize. ' , connection = 'Y' where id = '302963555';
update voters set connectioninfo = 'Known by: .How known:Maryam lives in the building. I dont know folks here but can try to help organize. ' , connection = 'Y' where id = '302981255';
update voters set connectioninfo = 'Known by: .How known:Maryam lives in the building. I dont know folks here but can try to help organize. ' , connection = 'Y' where id = '303561502';
update voters set connectioninfo = 'Known by: .How known:Lives in apartment next to Megan; will sign stuff but not active' , connection = 'Y' where id = '303642433';
update voters set connectioninfo = 'Known by: .How known:Lives in Megans building but she doesnt know him' , connection = 'Y' where id = '303763977';
update voters set connectioninfo = 'Known by: .How known:Lives in Megans building but I dont know him, this seems to be a duplicate' , connection = 'Y' where id = '303801339';
update voters set connectioninfo = 'Known by: .How known:Maryam lives in the building. I dont know folks here but can try to help organize. ' , connection = 'Y' where id = '304201289';
update voters set connectioninfo = 'Known by: .How known:Megans nextdoor neighbor, very nice and has signed stuff for me before; sisters with Roseanne, whom Megan doesnt get on with well.' , connection = 'Y' where id = '304950926';
update voters set connectioninfo = 'Known by: .How known:Maryam lives in the building. I dont know folks here but can try to help organize. ' , connection = 'Y' where id = '305221005';
update voters set connectioninfo = 'Known by: .How known:Lives in Megans building but she doesnt know them; may have moved because I think someone else lives in that apartment now but Im not sure.' , connection = 'Y' where id = '305454137';
update voters set connectioninfo = 'Known by: .How known:Lives in Megans building but she doesnt know them' , connection = 'Y' where id = '305685435';
update voters set connectioninfo = 'Known by: .How known:Maryam lives in the building. I dont know folks here but can try to help organize. ' , connection = 'Y' where id = '306198163';
update voters set connectioninfo = 'Known by: .How known:Maryam lives in the building. I dont know folks here but can try to help organize. ' , connection = 'Y' where id = '410315067';
update voters set connectioninfo = 'Known by: .How known:Maryam lives in the building. I dont know folks here but can try to help organize. ' , connection = 'Y' where id = '410615642';
update voters set connectioninfo = 'Known by: .How known:Maryam lives in the building. I dont know folks here but can try to help organize. ' , connection = 'Y' where id = '410700025';
update voters set connectioninfo = 'Known by: .How known:Maryam lives in the building. I dont know folks here but can try to help organize. ' , connection = 'Y' where id = '410732260';
update voters set connectioninfo = 'Known by: .How known:Maryam lives in the building. I dont know folks here but can try to help organize. ' , connection = 'Y' where id = '411002238';
update voters set connectioninfo = 'Known by: .How known:Maryam lives in the building. I dont know folks here but can try to help organize. ' , connection = 'Y' where id = '411112472';
update voters set connectioninfo = 'Known by: .How known:Maryam lives in the building. I dont know folks here but can try to help organize. ' , connection = 'Y' where id = '411123656';
update voters set connectioninfo = 'Known by: .How known:Lives in Megans building I dont know them, may have moved' , connection = 'Y' where id = '411292687';
update voters set connectioninfo = 'Known by: .How known:Lived in Megans building but must have moved because thats my SILs apartment now' , connection = 'Y' where id = '411320914';
update voters set connectioninfo = 'Known by: .How known:Maryam lives in the building. I dont know folks here but can try to help organize. ' , connection = 'Y' where id = '411327269';
update voters set connectioninfo = 'Known by: .How known:Maryam lives in the building. I dont know folks here but can try to help organize. ' , connection = 'Y' where id = '411338471';
update voters set connectioninfo = 'Known by: .How known:I dont know her personally but she lives in my building' , connection = 'Y' where id = '411362390';
update voters set connectioninfo = 'Known by: .How known:Maryam lives in the building. I dont know folks here but can try to help organize. ' , connection = 'Y' where id = '411365208';
update voters set connectioninfo = 'Known by: .How known:Maryam lives in the building. I dont know folks here but can try to help organize. ' , connection = 'Y' where id = '411566042';
update voters set connectioninfo = 'Known by: .How known:Megans building but I believe she moved because thats Pierres and Daphnas apartment now.' , connection = 'Y' where id = '411697074';
update voters set connectioninfo = 'Known by: .How known:Fahim' , connection = 'Y' where id = '411711949';
update voters set connectioninfo = 'Known by: .How known:Maryam lives in the building. I dont know folks here but can try to help organize. ' , connection = 'Y' where id = '412049127';
update voters set connectioninfo = 'Known by: .How known:Maryam lives in the building. I dont know folks here but can try to help organize. ' , connection = 'Y' where id = '412277546';
update voters set connectioninfo = 'Known by: .How known:Maryam lives in the building. I dont know folks here but can try to help organize. ' , connection = 'Y' where id = '412396695';
update voters set connectioninfo = 'Known by: .How known:Did live in Megans building, but moved' , connection = 'Y' where id = '412514803';
update voters set connectioninfo = 'Known by: .How known:Maryam lives in the building. I dont know folks here but can try to help organize. ' , connection = 'Y' where id = '412591362';
update voters set connectioninfo = 'Known by: .How known:Maryam lives in the building. I dont know folks here but can try to help organize. ' , connection = 'Y' where id = '412833456';
update voters set connectioninfo = 'Known by: .How known:Maryam lives in the building. I dont know folks here but can try to help organize. ' , connection = 'Y' where id = '413124224';
update voters set connectioninfo = 'Known by: all of usHow known:the zoom' , connection = 'Y' where id = '304567859';
update voters set connectioninfo = 'Known by: CarolinaHow known:Astoria Not For Sale' , connection = 'Y' where id = '305724108';
update voters set connectioninfo = 'Known by: CarolinaHow known:ex-boyfriends good friend' , connection = 'Y' where id = '300406304';
update voters set connectioninfo = 'Known by: CarolinaHow known:fellow actor' , connection = 'Y' where id = '412549809';
update voters set connectioninfo = 'Known by: CarolinaHow known:friend' , connection = 'Y' where id = '412442273';
update voters set connectioninfo = 'Known by: CarolinaHow known:friend and Jessicas good friend' , connection = 'Y' where id = '412045262';
update voters set connectioninfo = 'Known by: CarolinaHow known:friend of a friend' , connection = 'Y' where id = '411242278';
update voters set connectioninfo = 'Known by: CarolinaHow known:good friend' , connection = 'Y' where id = '410803564';
update voters set connectioninfo = 'Known by: CarolinaHow known:Good friends with her brother' , connection = 'Y' where id = '301313409';
update voters set connectioninfo = 'Known by: CarolinaHow known:he is Ava Eisensons partner' , connection = 'Y' where id = '412271660';
update voters set connectioninfo = 'Known by: CarolinaHow known:hes a casting director and indie filmmaker' , connection = 'Y' where id = '306124900';
update voters set connectioninfo = 'Known by: CarolinaHow known:I dont really know her, but we have a lot of friends in common' , connection = 'Y' where id = '412242206';
update voters set connectioninfo = 'Known by: CarolinaHow known:I hired him as an editor for my web series.' , connection = 'Y' where id = '412263597';
update voters set connectioninfo = 'Known by: CarolinaHow known:I kickboxed with her for years' , connection = 'Y' where id = '412008655';
update voters set connectioninfo = 'Known by: CarolinaHow known:I worked on a film with him' , connection = 'Y' where id = '410289857';
update voters set connectioninfo = 'Known by: CarolinaHow known:Ive heard about her...' , connection = 'Y' where id = '304564442';
update voters set connectioninfo = 'Known by: CarolinaHow known:she adopted kittens from me and the rescue' , connection = 'Y' where id = '413104749';
update voters set connectioninfo = 'Known by: CarolinaHow known:shes a fellow actor who is very politically active and has a following for politics in her circles; I just dont know how many folks of which are in Astoria' , connection = 'Y' where id = '410584083';
update voters set connectioninfo = 'Known by: CarolinaHow known:shes a film director; we belong to filmmaking groups together' , connection = 'Y' where id = '412201042';
update voters set connectioninfo = 'Known by: CarolinaHow known:shes a friend' , connection = 'Y' where id = '410410401';
update voters set connectioninfo = 'Known by: CarolinaHow known:shes a voiceover casting director' , connection = 'Y' where id = '410109231';
update voters set connectioninfo = 'Known by: CarolinaHow known:Shes an actor who has taken my headshots; I thought she moved to LA' , connection = 'Y' where id = '305479410';
update voters set connectioninfo = 'Known by: CarolinaHow known:shes my neighbor' , connection = 'Y' where id = '412287845';
update voters set connectioninfo = 'Known by: CarolinaHow known:through organizing in the union' , connection = 'Y' where id = '410279553';
update voters set connectioninfo = 'Known by: CarolinaHow known:went to college together' , connection = 'Y' where id = '410194424';
update voters set connectioninfo = 'Known by: CarolinaHow known:shes my trainer' , connection = 'Y' where id = '410925102';
update voters set connectioninfo = 'Known by: Carolina - hes Kates husbandHow known:I bother him and Kate almost every day' , connection = 'Y' where id = '412211371';
update voters set connectioninfo = 'Known by: Carolina has seen him on FBHow known:He posts on Astoria groups all the time. I dont know if he has sway with anyone, but he posts like he does ha' , connection = 'Y' where id = '305830388';
update voters set connectioninfo = 'Known by: Carolina/EvieHow known:through Astoria Not For Sale campaign' , connection = 'Y' where id = '412070847';
update voters set connectioninfo = 'Known by: Carolina/KateHow known:Friend' , connection = 'Y' where id = '411755981';
update voters set connectioninfo = 'Known by: Carolina/KateHow known:neighbor I dont know' , connection = 'Y' where id = '410669235';
update voters set connectioninfo = 'Known by: Carolina/KateHow known:neighbor we dont know' , connection = 'Y' where id = '302533846';
update voters set connectioninfo = 'Known by: Carolina/KateHow known:neighbor we dont know' , connection = 'Y' where id = '302710086';
update voters set connectioninfo = 'Known by: Carolina/KateHow known:neighbor we dont know' , connection = 'Y' where id = '303770746';
update voters set connectioninfo = 'Known by: Carolina/KateHow known:neighbor we dont know' , connection = 'Y' where id = '303998921';
update voters set connectioninfo = 'Known by: Carolina/KateHow known:neighbor we dont know' , connection = 'Y' where id = '304501682';
update voters set connectioninfo = 'Known by: Carolina/KateHow known:neighbor we dont know' , connection = 'Y' where id = '304735194';
update voters set connectioninfo = 'Known by: Carolina/KateHow known:neighbor we dont know' , connection = 'Y' where id = '305128399';
update voters set connectioninfo = 'Known by: Carolina/KateHow known:neighbor we dont know' , connection = 'Y' where id = '305556123';
update voters set connectioninfo = 'Known by: Carolina/KateHow known:neighbor we dont know' , connection = 'Y' where id = '410025410';
update voters set connectioninfo = 'Known by: Carolina/KateHow known:neighbor we dont know' , connection = 'Y' where id = '410113151';
update voters set connectioninfo = 'Known by: Carolina/KateHow known:neighbor we dont know' , connection = 'Y' where id = '410341532';
update voters set connectioninfo = 'Known by: Carolina/KateHow known:neighbor we dont know' , connection = 'Y' where id = '410504344';
update voters set connectioninfo = 'Known by: Carolina/KateHow known:neighbor we dont know' , connection = 'Y' where id = '410943432';
update voters set connectioninfo = 'Known by: Carolina/KateHow known:neighbor we dont know' , connection = 'Y' where id = '411077981';
update voters set connectioninfo = 'Known by: Carolina/KateHow known:neighbor we dont know' , connection = 'Y' where id = '411098379';
update voters set connectioninfo = 'Known by: Carolina/KateHow known:neighbor we dont know' , connection = 'Y' where id = '411147604';
update voters set connectioninfo = 'Known by: Carolina/KateHow known:neighbor we dont know' , connection = 'Y' where id = '411266724';
update voters set connectioninfo = 'Known by: Carolina/KateHow known:neighbor we dont know' , connection = 'Y' where id = '411455666';
update voters set connectioninfo = 'Known by: Carolina/KateHow known:neighbor we dont know' , connection = 'Y' where id = '411662870';
update voters set connectioninfo = 'Known by: Carolina/KateHow known:neighbor we dont know' , connection = 'Y' where id = '411663974';
update voters set connectioninfo = 'Known by: Carolina/KateHow known:neighbor we dont know' , connection = 'Y' where id = '411678545';
update voters set connectioninfo = 'Known by: Carolina/KateHow known:neighbor we dont know' , connection = 'Y' where id = '411991983';
update voters set connectioninfo = 'Known by: Carolina/KateHow known:neighbor we dont know' , connection = 'Y' where id = '412043103';
update voters set connectioninfo = 'Known by: Carolina/KateHow known:neighbor we dont know' , connection = 'Y' where id = '412127280';
update voters set connectioninfo = 'Known by: Carolina/KateHow known:neighbor we dont know' , connection = 'Y' where id = '412308709';
update voters set connectioninfo = 'Known by: Carolina/KateHow known:neighbor we dont know' , connection = 'Y' where id = '412599614';
update voters set connectioninfo = 'Known by: Carolina/KateHow known:neighbor we dont know' , connection = 'Y' where id = 'VV0200142';
update voters set connectioninfo = 'Known by: Carolina/KateHow known:neighbor we dont know' , connection = 'Y' where id = 'VV0291594';
update voters set connectioninfo = 'Known by: Carolina/KateHow known:neighbors we dont know' , connection = 'Y' where id = '300791078';
update voters set connectioninfo = 'Known by: Carolina/KateHow known:neighbors we dont know' , connection = 'Y' where id = 'N1027611';
update voters set connectioninfo = 'Known by: Carolina/MaryamHow known:Astoria Mutual Aid/ neighbor to Carolina' , connection = 'Y' where id = '305686653';
update voters set connectioninfo = 'Known by: EvieHow known:Organizing' , connection = 'Y' where id = '327399';
update voters set connectioninfo = 'Known by: EvieHow known:' , connection = 'Y' where id = '303041537';
update voters set connectioninfo = 'Known by: EvieHow known:' , connection = 'Y' where id = '305763021';
update voters set connectioninfo = 'Known by: EvieHow known:' , connection = 'Y' where id = '412835385';
update voters set connectioninfo = 'Known by: Evie, Carolina, Megan (I think)How known:AMAN and Open Streets' , connection = 'Y' where id = '410363303';
update voters set connectioninfo = 'Known by: Evie, I believeHow known:relatively certain this is the owner of Brass Owl' , connection = 'Y' where id = '410928189';
update voters set connectioninfo = 'Known by: Evie, MaryamHow known:Kids (Maryam) + Mutual Aid (Maryam + Evie)' , connection = 'Y' where id = '411341470';
update voters set connectioninfo = 'Known by: FahimHow known:family' , connection = 'Y' where id = '410882080';
update voters set connectioninfo = 'Known by: FahimHow known:family' , connection = 'Y' where id = '410883880';
update voters set connectioninfo = 'Known by: FahimHow known:family' , connection = 'Y' where id = '410914081';
update voters set connectioninfo = 'Known by: FahimHow known:' , connection = 'Y' where id = '410914080';
update voters set connectioninfo = 'Known by: FahimHow known:family' , connection = 'Y' where id = '410913513';
update voters set connectioninfo = 'Known by: FahimHow known:family' , connection = 'Y' where id = '410913517';
update voters set connectioninfo = 'Known by: FahimHow known:family' , connection = 'Y' where id = '412456586';
update voters set connectioninfo = 'Known by: FahimHow known:family' , connection = 'Y' where id = '412472336';
update voters set connectioninfo = 'Known by: GeogeHow known:Grade School classmate' , connection = 'Y' where id = '300042698';
update voters set connectioninfo = 'Known by: GeorgeHow known:Childhood friend of my sister; children are classmates at Immac' , connection = 'Y' where id = '302370488';
update voters set connectioninfo = 'Known by: GeorgeHow known:Children are friends; we hang out sometims (pre-covid)' , connection = 'Y' where id = '303573662';
update voters set connectioninfo = 'Known by: GeorgeHow known:Children are friends; we hang out sometims (pre-covid)' , connection = 'Y' where id = '304324443';
update voters set connectioninfo = 'Known by: GeorgeHow known:Children grade school classmates' , connection = 'Y' where id = '300721576';
update voters set connectioninfo = 'Known by: GeorgeHow known:Children in nursery together' , connection = 'Y' where id = '300167340';
update voters set connectioninfo = 'Known by: GeorgeHow known:Family Friend since childhood' , connection = 'Y' where id = '303131609';
update voters set connectioninfo = 'Known by: GeorgeHow known:Fathre of gradeschool classmate' , connection = 'Y' where id = 'C0144589';
update voters set connectioninfo = 'Known by: GeorgeHow known:Fomer tenant' , connection = 'Y' where id = '410068201';
update voters set connectioninfo = 'Known by: GeorgeHow known:Former tenant' , connection = 'Y' where id = '306381746';
update voters set connectioninfo = 'Known by: GeorgeHow known:Grade school friend' , connection = 'Y' where id = 'W1100996';
update voters set connectioninfo = 'Known by: GeorgeHow known:Grade school friends sibling' , connection = 'Y' where id = '300023061';
update voters set connectioninfo = 'Known by: GeorgeHow known:Immigration attorney; very involved - very ethical person; havent spoken to in about a year.   Daughters formerly in St Francis soccer together.' , connection = 'Y' where id = 'T3535008';
update voters set connectioninfo = 'Known by: GeorgeHow known:Involved in my mothers commnity group' , connection = 'Y' where id = '304626967';
update voters set connectioninfo = 'Known by: GeorgeHow known:is a play/screenwriter; fellow PS85 / IS141 parent' , connection = 'Y' where id = '305661710';
update voters set connectioninfo = 'Known by: GeorgeHow known:Mother of gradeschool classmate' , connection = 'Y' where id = '301567415';
update voters set connectioninfo = 'Known by: GeorgeHow known:Mother of gradeschool classmate, Casinelli co-owner' , connection = 'Y' where id = 'C0144590';
update voters set connectioninfo = 'Known by: GeorgeHow known:Mother of high school freind' , connection = 'Y' where id = '303104904';
update voters set connectioninfo = 'Known by: GeorgeHow known:MOthers good friend' , connection = 'Y' where id = 'Q0047730';
update voters set connectioninfo = 'Known by: GeorgeHow known:Mothers good friend' , connection = 'Y' where id = 'Q1356466';
update voters set connectioninfo = 'Known by: GeorgeHow known:My Mother' , connection = 'Y' where id = 'Q0800551';
update voters set connectioninfo = 'Known by: GeorgeHow known:My tenant' , connection = 'Y' where id = '413124358';
update voters set connectioninfo = 'Known by: GeorgeHow known:Pastor @ Immaculate Conception (this is rectory address); very close to my parents.' , connection = 'Y' where id = '303189472';
update voters set connectioninfo = 'Known by: GeorgeHow known:Sisters grade-school classmate' , connection = 'Y' where id = 'A1428764';
update voters set connectioninfo = 'Known by: Its me!How known:Maryam lives in the building. I dont know folks here but can try to help organize. ' , connection = 'Y' where id = '412296508';
update voters set connectioninfo = 'Known by: Izzy WeitzmanHow known:Father' , connection = 'Y' where id = '303184920';
update voters set connectioninfo = 'Known by: JessHow known:Lifeline Volunteer' , connection = 'Y' where id = '412029873';
update voters set connectioninfo = 'Known by: JessicaHow known:Connected Chef CSA customer' , connection = 'Y' where id = '410623750';
update voters set connectioninfo = 'Known by: JessicaHow known:Lifeline grocery volunteer' , connection = 'Y' where id = '410509471';
update voters set connectioninfo = 'Known by: JessicaHow known:Lifeline Volunteer' , connection = 'Y' where id = '305053912';
update voters set connectioninfo = 'Known by: JessicaHow known:Lifeline Volunteer' , connection = 'Y' where id = '306161057';
update voters set connectioninfo = 'Known by: JessicaHow known:Volunteers with Lifeline' , connection = 'Y' where id = '305304509';
update voters set connectioninfo = 'Known by: KATE How known:FRIEND AND COLLEAGUE' , connection = 'Y' where id = '306278634';
update voters set connectioninfo = 'Known by: Kim CalichioHow known:he is the owner of Astor Apiaries' , connection = 'Y' where id = '410935060';
update voters set connectioninfo = 'Known by: LitzaHow known:Alias husband' , connection = 'Y' where id = '411155257';
update voters set connectioninfo = 'Known by: LitzaHow known:Best friend from high school' , connection = 'Y' where id = '304794319';
update voters set connectioninfo = 'Known by: LitzaHow known:Book group' , connection = 'Y' where id = '410071000';
update voters set connectioninfo = 'Known by: LitzaHow known:Book group' , connection = 'Y' where id = '410159930';
update voters set connectioninfo = 'Known by: LitzaHow known:College friend' , connection = 'Y' where id = '410062887';
update voters set connectioninfo = 'Known by: LitzaHow known:CSA ages ago' , connection = 'Y' where id = '410357806';
update voters set connectioninfo = 'Known by: LitzaHow known:Dont know personally but kids go to PS85 and I know his wife (Abigail Haka) fairly well' , connection = 'Y' where id = '304607147';
update voters set connectioninfo = 'Known by: LitzaHow known:Fellow mom at PS85' , connection = 'Y' where id = '410129463';
update voters set connectioninfo = 'Known by: LitzaHow known:Fellow PS85 parent' , connection = 'Y' where id = '410165834';
update voters set connectioninfo = 'Known by: LitzaHow known:Fellow PS85 parent and previously on the PA. Knows a TON of people but may not be living in Astoria right now' , connection = 'Y' where id = '303688840';
update voters set connectioninfo = 'Known by: LitzaHow known:Former neighbor' , connection = 'Y' where id = '304088020';
update voters set connectioninfo = 'Known by: LitzaHow known:Former neighbor; husband Andrew Purdom owns Inside Astoria' , connection = 'Y' where id = '305008658';
update voters set connectioninfo = 'Known by: LitzaHow known:Friend' , connection = 'Y' where id = '305793135';
update voters set connectioninfo = 'Known by: LitzaHow known:Friend' , connection = 'Y' where id = '306317088';
update voters set connectioninfo = 'Known by: LitzaHow known:Friend [WL: I reached out to her a few months ago and she said she cant donate because of her city employment.]' , connection = 'Y' where id = '304513232';
update voters set connectioninfo = 'Known by: LitzaHow known:Friend of a friend, local mom' , connection = 'Y' where id = '305433654';
update voters set connectioninfo = 'Known by: LitzaHow known:Friend of friend, also worked on some school activism together' , connection = 'Y' where id = '410350890';
update voters set connectioninfo = 'Known by: LitzaHow known:Friend of friend; dont know her well directly but others might.' , connection = 'Y' where id = '410423647';
update voters set connectioninfo = 'Known by: LitzaHow known:Friend through synagogue' , connection = 'Y' where id = '304352125';
update voters set connectioninfo = 'Known by: LitzaHow known:Friend through synagogue' , connection = 'Y' where id = '304361760';
update voters set connectioninfo = 'Known by: LitzaHow known:Friends on Facebook' , connection = 'Y' where id = '305715882';
update voters set connectioninfo = 'Known by: LitzaHow known:From CSA years ago' , connection = 'Y' where id = '304705788';
update voters set connectioninfo = 'Known by: LitzaHow known:From CSA years ago; more recently encountered at events for Costa [I used to have dinners with her pretty regularly, before pandemic. I  can reach out[' , connection = 'Y' where id = '304705769';
update voters set connectioninfo = 'Known by: LitzaHow known:Good friend' , connection = 'Y' where id = '304534622';
update voters set connectioninfo = 'Known by: LitzaHow known:Good friend' , connection = 'Y' where id = '305516665';
update voters set connectioninfo = 'Known by: LitzaHow known:Has child in the same class at PS85' , connection = 'Y' where id = '305775598';
update voters set connectioninfo = 'Known by: LitzaHow known:Know through synagogue but also close friend' , connection = 'Y' where id = '304859302';
update voters set connectioninfo = 'Known by: LitzaHow known:Married to Alberta Mainieri-Burke; used to be on PS85 PA' , connection = 'Y' where id = '410837690';
update voters set connectioninfo = 'Known by: LitzaHow known:Married to an old friend of mine' , connection = 'Y' where id = '411292330';
update voters set connectioninfo = 'Known by: LitzaHow known:Mutual friend' , connection = 'Y' where id = '306184958';
update voters set connectioninfo = 'Known by: LitzaHow known:Mutual friends' , connection = 'Y' where id = '306181364';
update voters set connectioninfo = 'Known by: LitzaHow known:My sons first babysitter' , connection = 'Y' where id = '410994149';
update voters set connectioninfo = 'Known by: LitzaHow known:Neighbor and very interested in political issues' , connection = 'Y' where id = '306144724';
update voters set connectioninfo = 'Known by: LitzaHow known:Neighbor, retired dentist, hospitalized for Covid this past spring so health care might be important issue' , connection = 'Y' where id = '301638796';
update voters set connectioninfo = 'Known by: LitzaHow known:Neighbor; shes also a former PS85 teacher' , connection = 'Y' where id = '302758551';
update voters set connectioninfo = 'Known by: LitzaHow known:Not sure I do, but she apparently lives directly across the street from me so maybe I should!' , connection = 'Y' where id = '410148116';
update voters set connectioninfo = 'Known by: LitzaHow known:Organized a social justice seder with him for a couple of years' , connection = 'Y' where id = '306149102';
update voters set connectioninfo = 'Known by: LitzaHow known:Parent at PS85 and good friend' , connection = 'Y' where id = '305728175';
update voters set connectioninfo = 'Known by: LitzaHow known:Parent at PS85 and good friend' , connection = 'Y' where id = '305841348';
update voters set connectioninfo = 'Known by: LitzaHow known:PS85 parent' , connection = 'Y' where id = '305111739';
update voters set connectioninfo = 'Known by: LitzaHow known:PS85 parent' , connection = 'Y' where id = '305163804';
update voters set connectioninfo = 'Known by: LitzaHow known:PS85 Parent' , connection = 'Y' where id = '306241247';
update voters set connectioninfo = 'Known by: LitzaHow known:PS85 parent' , connection = 'Y' where id = '306267395';
update voters set connectioninfo = 'Known by: LitzaHow known:Slightly through synagogue; shes also active in online parent groups' , connection = 'Y' where id = '303164610';
update voters set connectioninfo = 'Known by: LitzaHow known:Synagogue' , connection = 'Y' where id = '300770776';
update voters set connectioninfo = 'Known by: LitzaHow known:Synagogue' , connection = 'Y' where id = '304178419';
update voters set connectioninfo = 'Known by: LitzaHow known:Synagogue' , connection = 'Y' where id = '306297645';
update voters set connectioninfo = 'Known by: LitzaHow known:Synagogue' , connection = 'Y' where id = 'Q1071483';
update voters set connectioninfo = 'Known by: LitzaHow known:Synagogue and PS85. Shes a comedy writer and her husband is a Dr at Bellevue' , connection = 'Y' where id = '411255105';
update voters set connectioninfo = 'Known by: LitzaHow known:Synagogue; married to Nadine Graham-Kaplan' , connection = 'Y' where id = '303941673';
update voters set connectioninfo = 'Known by: LitzaHow known:Tenant of Laura Mello' , connection = 'Y' where id = '306276997';
update voters set connectioninfo = 'Known by: LitzaHow known:Theyve moved' , connection = 'Y' where id = '410956877';
update voters set connectioninfo = 'Known by: LitzaHow known:Theyve moved' , connection = 'Y' where id = '410956878';
update voters set connectioninfo = 'Known by: LitzaHow known:Through mutual friend and synagogue' , connection = 'Y' where id = '304794594';
update voters set connectioninfo = 'Known by: LitzaHow known:Very involved PS85 parent' , connection = 'Y' where id = '304853697';
update voters set connectioninfo = 'Known by: LitzaHow known:Former PS85 PA president and close friend' , connection = 'Y' where id = '304950877';
update voters set connectioninfo = 'Known by: LitzaHow known:Neighbor and friend' , connection = 'Y' where id = '306123661';
update voters set connectioninfo = 'Known by: LitzaHow known:Piano teacher to my sons' , connection = 'Y' where id = '411169984';
update voters set connectioninfo = 'Known by: Litza (among others)How known:Friend & worked on other political stuff together' , connection = 'Y' where id = '304863912';
update voters set connectioninfo = 'Known by: Litza (among others)How known:Met through synagogue and now good friend' , connection = 'Y' where id = '304545315';
update voters set connectioninfo = 'Known by: Litza (among others)How known:PS85' , connection = 'Y' where id = '303080708';
update voters set connectioninfo = 'Known by: Litza (and I think Wendy knows better)How known:CSA--[WL--I think she lives in Spain now! I hit her up for a donation but Ill ask her again]' , connection = 'Y' where id = '304122579';
update voters set connectioninfo = 'Known by: Litza and CarolinaHow known:Fellow PS85 parent/ good friend of Carolina' , connection = 'Y' where id = '410509439';
update voters set connectioninfo = 'Known by: Litza and probably othersHow known:Fellow PS85 mom' , connection = 'Y' where id = '306197804';
update voters set connectioninfo = 'Known by: Litza via AliaHow known:Met her at an event at Alias house' , connection = 'Y' where id = '303459660';
update voters set connectioninfo = 'Known by: Litza, JessicaHow known:In a book group together briefly, also a lifeline volunteer' , connection = 'Y' where id = '304043920';
update voters set connectioninfo = 'Known by: LylaHow known:Friends mom' , connection = 'Y' where id = '413013044';
update voters set connectioninfo = 'Known by: LylaHow known:Lylas dad' , connection = 'Y' where id = '304605040';
update voters set connectioninfo = 'Known by: LylaHow known:Lylas mom' , connection = 'Y' where id = '304930262';
update voters set connectioninfo = 'Known by: MaryamHow known:Maryam lives in the building. I dont know folks here but can try to help organize. ' , connection = 'Y' where id = '410064136';
update voters set connectioninfo = 'Known by: Maryam?/ Carolina, JessHow known:Carolina vaguely knows her, Maryam likely much more. She is DSA I believe, so we may need to court her, Jess talks to her weekly with lifeline' , connection = 'Y' where id = '413162665';
update voters set connectioninfo = 'Known by: MeganHow known:Lives in Megans building, we are close; shes very politically active' , connection = 'Y' where id = '1967264';
update voters set connectioninfo = 'Known by: MeganHow known:Friends, kids went to same school' , connection = 'Y' where id = '410900947';
update voters set connectioninfo = 'Known by: MeganHow known:Friends, kids were in same daycare' , connection = 'Y' where id = '300954657';
update voters set connectioninfo = 'Known by: MeganHow known:Lives in Megans building but she doesnt know him' , connection = 'Y' where id = '300193119';
update voters set connectioninfo = 'Known by: MeganHow known:Lives in my building. Were friendly' , connection = 'Y' where id = 'VV0219500';
update voters set connectioninfo = 'Known by: MeganHow known:Megan, she signs stuff for me and is close with Noreen, but doesnt get involved in politics because she was a volunteer for Robert Kennedy and when she died it broke her heart.' , connection = 'Y' where id = 'X1148998';
update voters set connectioninfo = 'Known by: MeganHow known:I dont know her personally but she lives in my building' , connection = 'Y' where id = '411579075';
update voters set connectioninfo = 'Known by: MeganHow known:Lives in my building, friendly with him, he signs political stuff for me sometimes and is into growing stuff' , connection = 'Y' where id = '412025686';
update voters set connectioninfo = 'Known by: MeganHow known:Lives in Megans building but I dont know him and he may have moved - his address is in our old format' , connection = 'Y' where id = '412232689';
update voters set connectioninfo = 'Known by: MeganHow known:Lives in my building' , connection = 'Y' where id = '412427789';
update voters set connectioninfo = 'Known by: MeganHow known:Lives in Megans building, but I dont know her, and she may have moved.' , connection = 'Y' where id = '412437841';
update voters set connectioninfo = 'Known by: MeganHow known:Lives in Megans building; will sign stuff but very reserved. Loves records.' , connection = 'Y' where id = '412973897';
update voters set connectioninfo = 'Known by: MeganHow known:Lives in my building but I dont know her' , connection = 'Y' where id = '412988460';
update voters set connectioninfo = 'Known by: MeganHow known:Lives in Megans building - were friendly and she wants to get more involved in gardening, would probably come to an event' , connection = 'Y' where id = '413007375';
update voters set connectioninfo = 'Known by: MeganHow known:Lives in my building but Im not sure if he still lives here' , connection = 'Y' where id = '413092777';
update voters set connectioninfo = 'Known by: MeganHow known:Megans SIL' , connection = 'Y' where id = '413248436';
update voters set connectioninfo = 'Known by: MeganHow known:Megans neighbor; we are friendly, but last I checked hes registered in NJ; maybe that changed' , connection = 'Y' where id = '413268530';
update voters set connectioninfo = 'Known by: MeganHow known:Megans neighbor; were friendly and shes done political stuff for me before' , connection = 'Y' where id = '413301088';
update voters set connectioninfo = 'Known by: MeganHow known:Lives in Megans building but I dont know him' , connection = 'Y' where id = '413343498';
update voters set connectioninfo = 'Known by: MeganHow known:Lives in Megans building but she doesnt know him, he may have moved' , connection = 'Y' where id = '413634647';
update voters set connectioninfo = 'Known by: MeganHow known:Lives in Megans building but she doesnt know him' , connection = 'Y' where id = '413717121';
update voters set connectioninfo = 'Known by: MeganHow known:Moved - Megan lives in his old apartment' , connection = 'Y' where id = '413965012';
update voters set connectioninfo = 'Known by: MeganHow known:Lives in my building, were not close but shes close with my friend and neighbor Noreen, whos very politically active' , connection = 'Y' where id = 'Q1041580';
update voters set connectioninfo = 'Known by: MeganHow known:Lives in Megans building but can be hard to get along with. Will sometimes sign stuff but usually not.' , connection = 'Y' where id = 'Q1055615';
update voters set connectioninfo = 'Known by: MeganHow known:Lives in my building but I dont know him' , connection = 'Y' where id = 'VV0179241';
update voters set connectioninfo = 'Known by: MeganHow known:Megans building but doesnt know him and isnt sure if he still lives here.' , connection = 'Y' where id = 'VV0218522';
update voters set connectioninfo = 'Known by: Most of us I thinkHow known:Local political activities' , connection = 'Y' where id = '411612830';
update voters set connectioninfo = 'Known by: to Wendy LehmannHow known:Ed is an editor for Sesame Street, did a spot with me for Creative Resistance but said was too busy to do more. Ill email him. He was upset about Zohran winning' , connection = 'Y' where id = '306168087';
update voters set connectioninfo = 'Known by: WendyHow known:Married to him, will ask him to donate--Wendy' , connection = 'Y' where id = '304148550';
update voters set connectioninfo = 'Known by: Wendy LehmannHow known:We worked together and are friends' , connection = 'Y' where id = '300695516';
update voters set connectioninfo = 'Known by: Wendy Lehmann: PS85/IS141 parent friendHow known:Neighbors, baseball/football team friends. Ill email him' , connection = 'Y' where id = '410200703';
