DROP TABLE IF EXISTS `voterdatareach` ;

CREATE TABLE `voterdatareach` 
(
`LALVOTERID` varchar(14) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL,
`Voters_StateVoterID` varchar(20) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL,
`Voters_CountyVoterID` varchar(12) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL,
`Walking_List_Sequence` varchar(7) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL,
`HH Code` varchar(10) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL,
`VoterTelephones_FullPhone` varchar(14) CHARACTER SET utf8 COLLATE utf8_bin ,
`VoterTelephones_TelConfidenceCode` varchar(1) CHARACTER SET utf8 COLLATE utf8_bin ,
`VoterTelephones_TelCellFlag` varchar(1) CHARACTER SET utf8 COLLATE utf8_bin ,
`View_Ops_CellPhone_FullPhone` varchar(14) CHARACTER SET utf8 COLLATE utf8_bin ,
`Voters_FirstName` varchar(23) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL,
`Voters_MiddleName` varchar(29) CHARACTER SET utf8 COLLATE utf8_bin ,
`Voters_LastName` varchar(27) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL,
`Voters Name Suffix` varchar(3) CHARACTER SET utf8 COLLATE utf8_bin ,
`Residence_Addresses_AddressLine` varchar(32) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL,
`Residence_Addresses_City` varchar(16) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL,
`Residence_Addresses_State` varchar(2) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL,
`Zip` varchar(5) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL,
`Residence_Addresses_HouseNumber` varchar(5) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL,
`Residence_Addresses_StreetName` varchar(24) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL,
`Residence_Addresses_Designator` varchar(4) CHARACTER SET utf8 COLLATE utf8_bin ,
`Residence_Addresses_SuffixDirection` varchar(1) CHARACTER SET utf8 COLLATE utf8_bin ,
`Residence_Addresses_ApartmentNum` varchar(18) CHARACTER SET utf8 COLLATE utf8_bin ,
`Residence_Addresses_CensusTract` varchar(5) CHARACTER SET utf8 COLLATE utf8_bin ,
`Residence_Addresses_CensusBlockGroup` varchar(1) CHARACTER SET utf8 COLLATE utf8_bin ,
`Residence_Addresses_CensusBlock` varchar(4) CHARACTER SET utf8 COLLATE utf8_bin ,
`Latitude` varchar(9) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL,
`Longitude` varchar(10) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL,
`Residence_Addresses_ZipPlus4` varchar(4) CHARACTER SET utf8 COLLATE utf8_bin ,
`Residence_Addresses_City_b` varchar(16) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL,
`Residence_Addresses_State_b` varchar(2) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL,
`Zip_b` varchar(5) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL,
`Voters_BirthDate` date ,
`Voters_OfficialRegDate` date NOT NULL,
`Voters_Age` varchar(5) CHARACTER SET utf8 COLLATE utf8_bin ,
`Ethnic_Description` varchar(39) CHARACTER SET utf8 COLLATE utf8_bin ,
`Broad Ethnic Groupings` varchar(23) CHARACTER SET utf8 COLLATE utf8_bin ,
`Mailing_Addresses_AddressLine` varchar(39) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL,
`Mailing_Addresses_ExtraAddressLine` varchar(19) CHARACTER SET utf8 COLLATE utf8_bin ,
`Mailing_Addresses_City` varchar(16) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL,
`Mailing_Addresses_State` varchar(2) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL,
`Mailing_Addresses_Zip` varchar(5) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL,
`Household Primary Language` varchar(36) CHARACTER SET utf8 COLLATE utf8_bin ,
`Hispanic Country Origin` varchar(18) CHARACTER SET utf8 COLLATE utf8_bin ,
`Cable or Dish Television` varchar(14) CHARACTER SET utf8 COLLATE utf8_bin ,
`Religions_Description` varchar(16) CHARACTER SET utf8 COLLATE utf8_bin ,
`AbsenteeTypes_Description` varchar(14) CHARACTER SET utf8 COLLATE utf8_bin ,
`VoterParties_Change_Changed_Party` varchar(25) CHARACTER SET utf8 COLLATE utf8_bin ,
`Voters_VotingPerformanceEvenYearGeneral` varchar(12) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL,
`Voters_VotingPerformanceEvenYearPrimary` varchar(12) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL,
`Voters_VotingPerformanceEvenYearGeneralAndPrimary` varchar(12) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL,
`Voters_VotingPerformanceMinorElection` varchar(12) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL,
`AddressDistricts_Change_Changed_County` varchar(35) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL,
`AddressDistricts_Change_Changed_CD` varchar(35) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL,
`AddressDistricts_Change_Changed_SD` varchar(35) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL,
`AddressDistricts_Change_Changed_HD` varchar(35) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL,
`Voters_Gender` varchar(1) CHARACTER SET utf8 COLLATE utf8_bin ,
`MilitaryStatus_Description` varchar(8) CHARACTER SET utf8 COLLATE utf8_bin ,
`MaritalStatus_Description` varchar(17) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL,
`Residence_Families_HHCount` varchar(1) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL,
`Residence_HHParties_Description` varchar(37) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL,
`Residence_HHGender_Description` varchar(22) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL,
`Congressional_District` varchar(2) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL,
`State_Senate_District` varchar(2) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL,
`State_House_District` varchar(2) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL,
`Precinct` varchar(16) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL,
`Vote_Frequency` varchar(1) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL,
`PRI_BLT_2008-02-05` varchar(12) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL,
`PRI_BLT_2008-09-09` varchar(12) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL,
`PRI_BLT_2009-09-15` varchar(12) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL,
`PRI_BLT_2010-09-14` varchar(12) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL,
`PRI_BLT_2011-09-13` varchar(12) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL,
`PRI_BLT_2012-04-24` varchar(12) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL,
`PRI_BLT_2012-06-26` varchar(12) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL,
`PRI_BLT_2012-09-13` varchar(12) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL,
`PRI_BLT_2013-09-10` varchar(12) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL,
`PRI_BLT_2014-06-24` varchar(12) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL,
`PRI_BLT_2014-09-09` varchar(12) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL,
`PRI_BLT_2015-09-10` varchar(12) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL,
`PRI_BLT_2016-04-19` varchar(12) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL,
`PRI_BLT_2016-06-28` varchar(12) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL,
`PRI_BLT_2016-09-13` varchar(12) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL,
`PRI_BLT_2017-09-12` varchar(12) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL,
`PRI_BLT_2018-06-26` varchar(12) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL,
`PRI_BLT_2018-09-13` varchar(12) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL,
`PRI_BLT_2019-06-25` varchar(12) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL,
`PRI_BLT_2020-06-23` varchar(12) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL,
`General_1985-11-05` varchar(0) CHARACTER SET utf8 COLLATE utf8_bin ,
`General_1986-11-04` varchar(0) CHARACTER SET utf8 COLLATE utf8_bin ,
`General_1987-11-03` varchar(0) CHARACTER SET utf8 COLLATE utf8_bin ,
`General_1988-11-08` varchar(1) CHARACTER SET utf8 COLLATE utf8_bin ,
`General_1989-11-07` varchar(1) CHARACTER SET utf8 COLLATE utf8_bin ,
`General_1990-11-06` varchar(1) CHARACTER SET utf8 COLLATE utf8_bin ,
`General_1991-11-05` varchar(1) CHARACTER SET utf8 COLLATE utf8_bin ,
`General_1992-11-03` varchar(1) CHARACTER SET utf8 COLLATE utf8_bin ,
`General_1993-11-02` varchar(1) CHARACTER SET utf8 COLLATE utf8_bin ,
`General_1994-11-08` varchar(1) CHARACTER SET utf8 COLLATE utf8_bin ,
`General_1995-11-07` varchar(1) CHARACTER SET utf8 COLLATE utf8_bin ,
`General_1996-11-05` varchar(1) CHARACTER SET utf8 COLLATE utf8_bin ,
`General_1997-11-04` varchar(1) CHARACTER SET utf8 COLLATE utf8_bin ,
`General_1998-11-03` varchar(1) CHARACTER SET utf8 COLLATE utf8_bin ,
`General_1999-11-02` varchar(1) CHARACTER SET utf8 COLLATE utf8_bin ,
`General_2000-11-07` varchar(1) CHARACTER SET utf8 COLLATE utf8_bin ,
`General_2001-11-06` varchar(1) CHARACTER SET utf8 COLLATE utf8_bin ,
`General_2002-11-05` varchar(1) CHARACTER SET utf8 COLLATE utf8_bin ,
`General_2003-11-04` varchar(1) CHARACTER SET utf8 COLLATE utf8_bin ,
`General_2004-11-02` varchar(1) CHARACTER SET utf8 COLLATE utf8_bin ,
`General_2005-11-08` varchar(1) CHARACTER SET utf8 COLLATE utf8_bin ,
`General_2006-11-07` varchar(1) CHARACTER SET utf8 COLLATE utf8_bin ,
`General_2007-11-06` varchar(1) CHARACTER SET utf8 COLLATE utf8_bin ,
`General_2008-11-04` varchar(1) CHARACTER SET utf8 COLLATE utf8_bin ,
`General_2009-11-03` varchar(1) CHARACTER SET utf8 COLLATE utf8_bin ,
`General_2010-11-02` varchar(1) CHARACTER SET utf8 COLLATE utf8_bin ,
`General_2011-11-08` varchar(1) CHARACTER SET utf8 COLLATE utf8_bin ,
`General_2012-11-06` varchar(1) CHARACTER SET utf8 COLLATE utf8_bin ,
`General_2013-11-05` varchar(1) CHARACTER SET utf8 COLLATE utf8_bin ,
`General_2014-11-04` varchar(1) CHARACTER SET utf8 COLLATE utf8_bin ,
`General_2015-11-03` varchar(1) CHARACTER SET utf8 COLLATE utf8_bin ,
`General_2016-11-08` varchar(1) CHARACTER SET utf8 COLLATE utf8_bin ,
`General_2017-11-07` varchar(1) CHARACTER SET utf8 COLLATE utf8_bin ,
`General_2018-11-06` varchar(1) CHARACTER SET utf8 COLLATE utf8_bin ,
`General_2019-11-05` varchar(1) CHARACTER SET utf8 COLLATE utf8_bin ,
`Presidential_Primary_1992-04-07` varchar(1) CHARACTER SET utf8 COLLATE utf8_bin ,
`Presidential_Primary_1996-03-07` varchar(1) CHARACTER SET utf8 COLLATE utf8_bin ,
`Presidential_Primary_2000-03-07` varchar(1) CHARACTER SET utf8 COLLATE utf8_bin ,
`Presidential_Primary_2004-03-02` varchar(1) CHARACTER SET utf8 COLLATE utf8_bin ,
`Presidential_Primary_2008-02-05` varchar(1) CHARACTER SET utf8 COLLATE utf8_bin ,
`Presidential_Primary_2012-04-24` varchar(1) CHARACTER SET utf8 COLLATE utf8_bin ,
`Presidential_Primary_2016-04-19` varchar(1) CHARACTER SET utf8 COLLATE utf8_bin ,
`Presidential_Primary_2020-06-23` varchar(1) CHARACTER SET utf8 COLLATE utf8_bin ,
`Special_2019-02-26` varchar(1) CHARACTER SET utf8 COLLATE utf8_bin ,
`Runoff_2001-10-11` varchar(1) CHARACTER SET utf8 COLLATE utf8_bin ,
`Runoff_2009-09-29` varchar(1) CHARACTER SET utf8 COLLATE utf8_bin ,
`Runoff_2013-10-01` varchar(1) CHARACTER SET utf8 COLLATE utf8_bin ,
`PresenceOfChildrenCode` varchar(37) CHARACTER SET utf8 COLLATE utf8_bin ,
`ISPSA` varchar(1) CHARACTER SET utf8 COLLATE utf8_bin ,
`Home Purchase Price` VARCHAR(10) CHARACTER SET utf8 COLLATE utf8_bin ,
`Land Value` VARCHAR(10) CHARACTER SET utf8 COLLATE utf8_bin ,
`Home Owner/Renter` varchar(16) CHARACTER SET utf8 COLLATE utf8_bin ,
`Property Type` varchar(22) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL,
`DwellingType` varchar(27) CHARACTER SET utf8 COLLATE utf8_bin ,
`HomePurchaseDate` date ,
`EstHomeValue` varchar(20) CHARACTER SET utf8 COLLATE utf8_bin ,
`MedianEducationYears` varchar(2) CHARACTER SET utf8 COLLATE utf8_bin ,
`Net Worth` varchar(14) CHARACTER SET utf8 COLLATE utf8_bin ,
`Investor` varchar(3) CHARACTER SET utf8 COLLATE utf8_bin ,
`Likely Union Member` varchar(3) CHARACTER SET utf8 COLLATE utf8_bin ,
`Business Owner` varchar(3) CHARACTER SET utf8 COLLATE utf8_bin ,
`EstimatedIncomeAmount` varchar(10) CHARACTER SET utf8 COLLATE utf8_bin ,
`EstimatedIncome` varchar(17) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL,
`Education` varchar(46) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL,
`OccupationIndustry` varchar(21) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL,
`Occupation` varchar(44) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL,
`ReligiousContributorInHome` varchar(33) CHARACTER SET utf8 COLLATE utf8_bin ,
`PoliticalContributerInHome` varchar(33) CHARACTER SET utf8 COLLATE utf8_bin ,
`DonatesEnvironmentCauseInHome` varchar(7) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL,
`DonatesToCharityInHome` varchar(7) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL,
`Donates to Animal Welfare` varchar(3) CHARACTER SET utf8 COLLATE utf8_bin ,
`Donates to Arts and Culture` varchar(3) CHARACTER SET utf8 COLLATE utf8_bin ,
`Donates to Childrens Causes` varchar(3) CHARACTER SET utf8 COLLATE utf8_bin ,
`Donates to Healthcare` varchar(3) CHARACTER SET utf8 COLLATE utf8_bin ,
`Donates to International Aid Causes` varchar(3) CHARACTER SET utf8 COLLATE utf8_bin ,
`Donates to Veterans Causes` varchar(3) CHARACTER SET utf8 COLLATE utf8_bin ,
`Donates to Wildlife Preservation` varchar(3) CHARACTER SET utf8 COLLATE utf8_bin ,
`Donates to Conservative Causes` varchar(3) CHARACTER SET utf8 COLLATE utf8_bin ,
`Donates to Liberal Causes` varchar(3) CHARACTER SET utf8 COLLATE utf8_bin ,
`Donates to Local Community` varchar(3) CHARACTER SET utf8 COLLATE utf8_bin ,
`StateIncomeDecile` varchar(18) CHARACTER SET utf8 COLLATE utf8_bin ,
`PcntHHWithChildren` varchar(4) CHARACTER SET utf8 COLLATE utf8_bin ,
`PcntHHSpanishSpeaking` varchar(4) CHARACTER SET utf8 COLLATE utf8_bin ,
`MosaicZ4` varchar(24) CHARACTER SET utf8 COLLATE utf8_bin ,
`Horse Owner` varchar(3) CHARACTER SET utf8 COLLATE utf8_bin ,
`Cat Owner` varchar(3) CHARACTER SET utf8 COLLATE utf8_bin ,
`Dog Owner` varchar(3) CHARACTER SET utf8 COLLATE utf8_bin ,
`Other Pet Owner` varchar(3) CHARACTER SET utf8 COLLATE utf8_bin ,
`Home Office` varchar(3) CHARACTER SET utf8 COLLATE utf8_bin ,
`Book Buyer In Home` varchar(24) CHARACTER SET utf8 COLLATE utf8_bin ,
`Family Magazine In Home` varchar(36) CHARACTER SET utf8 COLLATE utf8_bin ,
`Female Oriented Magazine In Home` varchar(27) CHARACTER SET utf8 COLLATE utf8_bin ,
`Religious Magazine In Home` varchar(30) CHARACTER SET utf8 COLLATE utf8_bin ,
`Gardening Magazine In Home` varchar(30) CHARACTER SET utf8 COLLATE utf8_bin ,
`Culinary Interest Magazine In Home` varchar(29) CHARACTER SET utf8 COLLATE utf8_bin ,
`Health Fitness Magazine In Home` varchar(39) CHARACTER SET utf8 COLLATE utf8_bin ,
`Do It Yourselfer Magazine In Home` varchar(35) CHARACTER SET utf8 COLLATE utf8_bin ,
`Financial Magazine In Home` varchar(30) CHARACTER SET utf8 COLLATE utf8_bin ,
`Computer Owner In Home` varchar(7) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL,
`Household Composition` varchar(40) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL,
`Languages` varchar(14) CHARACTER SET utf8 COLLATE utf8_bin ,
`Dwelling Unit Size` varchar(24) CHARACTER SET utf8 COLLATE utf8_bin ,
`Upscale Buyer In Home` varchar(31) CHARACTER SET utf8 COLLATE utf8_bin ,
`Upscale Male Buyer In Home` varchar(31) CHARACTER SET utf8 COLLATE utf8_bin ,
`Upscale Female Buyer In Home` varchar(31) CHARACTER SET utf8 COLLATE utf8_bin ,
`Buyer of Antiques in Household` varchar(3) CHARACTER SET utf8 COLLATE utf8_bin ,
`Buyer of Art in Household` varchar(3) CHARACTER SET utf8 COLLATE utf8_bin ,
`General Collector in Household` varchar(3) CHARACTER SET utf8 COLLATE utf8_bin ,
`Stamps Collector in Household` varchar(3) CHARACTER SET utf8 COLLATE utf8_bin ,
`Coins Collector in Household` varchar(3) CHARACTER SET utf8 COLLATE utf8_bin ,
`Arts Collector in Household` varchar(3) CHARACTER SET utf8 COLLATE utf8_bin ,
`Antiques Collector in Household` varchar(3) CHARACTER SET utf8 COLLATE utf8_bin ,
`Avid Collector in Household` varchar(3) CHARACTER SET utf8 COLLATE utf8_bin ,
`Sports Collector in Household` varchar(3) CHARACTER SET utf8 COLLATE utf8_bin ,
`Military Collector in Household` varchar(3) CHARACTER SET utf8 COLLATE utf8_bin ,
`Interest in Current Affairs Politics In Household` varchar(3) CHARACTER SET utf8 COLLATE utf8_bin ,
`General Reading in Household` varchar(3) CHARACTER SET utf8 COLLATE utf8_bin ,
`Religious Reading in Household` varchar(3) CHARACTER SET utf8 COLLATE utf8_bin ,
`Fiction Science Reading in Household` varchar(3) CHARACTER SET utf8 COLLATE utf8_bin ,
`Magazines Reading in Household` varchar(3) CHARACTER SET utf8 COLLATE utf8_bin ,
`Books Audio Reading in Household` varchar(3) CHARACTER SET utf8 COLLATE utf8_bin ,
`Gun Owner` varchar(7) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL,
`Veteran` varchar(7) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL,
`Interest in History Military in Household` varchar(3) CHARACTER SET utf8 COLLATE utf8_bin ,
`Interest in Religious Inspirational in Household` varchar(3) CHARACTER SET utf8 COLLATE utf8_bin ,
`Interest in Science Space in Household` varchar(3) CHARACTER SET utf8 COLLATE utf8_bin ,
`Interest in Education Online in Household` varchar(3) CHARACTER SET utf8 COLLATE utf8_bin ,
`Interest in Electronic Gaming in Household` varchar(3) CHARACTER SET utf8 COLLATE utf8_bin ,
`Interest in Theater Performing Arts in Household` varchar(3) CHARACTER SET utf8 COLLATE utf8_bin ,
`Interest in the Arts in Household` varchar(3) CHARACTER SET utf8 COLLATE utf8_bin ,
`Interest in Musical Instruments in Household` varchar(3) CHARACTER SET utf8 COLLATE utf8_bin ,
`Interest in Home Repair in Household` varchar(3) CHARACTER SET utf8 COLLATE utf8_bin ,
`Interest in Auto Work in Household` varchar(3) CHARACTER SET utf8 COLLATE utf8_bin ,
`Interest in Sewing Knitting in Household` varchar(3) CHARACTER SET utf8 COLLATE utf8_bin ,
`Interest in Woodworking in Household` varchar(3) CHARACTER SET utf8 COLLATE utf8_bin ,
`Interest in Photography in Household` varchar(3) CHARACTER SET utf8 COLLATE utf8_bin ,
`Interest in Aviation in Household` varchar(3) CHARACTER SET utf8 COLLATE utf8_bin ,
`Interest in House Plants in Household` varchar(0) CHARACTER SET utf8 COLLATE utf8_bin ,
`Interest in Crafts in Household` varchar(3) CHARACTER SET utf8 COLLATE utf8_bin ,
`Interest in Gardening in Household` varchar(3) CHARACTER SET utf8 COLLATE utf8_bin ,
`Interest in Photography Video in Household` varchar(3) CHARACTER SET utf8 COLLATE utf8_bin ,
`Interest in Smoking in Household` varchar(3) CHARACTER SET utf8 COLLATE utf8_bin ,
`Interest in Home Furnishings in Household` varchar(3) CHARACTER SET utf8 COLLATE utf8_bin ,
`Interest in Home Improvement in Household` varchar(3) CHARACTER SET utf8 COLLATE utf8_bin ,
`Interest in Food Wines in Household` varchar(3) CHARACTER SET utf8 COLLATE utf8_bin ,
`Interest in Cooking General in Household` varchar(3) CHARACTER SET utf8 COLLATE utf8_bin ,
`Interest in Cooking Gourmet in Household` varchar(3) CHARACTER SET utf8 COLLATE utf8_bin ,
`Interest in Foods Natural in Household` varchar(3) CHARACTER SET utf8 COLLATE utf8_bin ,
`Interest in BoardGames Puzzles in Household` varchar(3) CHARACTER SET utf8 COLLATE utf8_bin ,
`Interest in Gaming Casino in Household` varchar(3) CHARACTER SET utf8 COLLATE utf8_bin ,
`Interest in Sweepstakes Contests in Household` varchar(3) CHARACTER SET utf8 COLLATE utf8_bin ,
`Interest in Travel Domestic in Household` varchar(3) CHARACTER SET utf8 COLLATE utf8_bin ,
`Interest in Travel International in Household` varchar(3) CHARACTER SET utf8 COLLATE utf8_bin ,
`Interest in Travel Cruise in Household` varchar(3) CHARACTER SET utf8 COLLATE utf8_bin ,
`Interest in Exercise Health in Household` varchar(3) CHARACTER SET utf8 COLLATE utf8_bin ,
`Interest in Exercise Running Jogging in Household` varchar(3) CHARACTER SET utf8 COLLATE utf8_bin ,
`Interest in Exercise Walking in Household` varchar(3) CHARACTER SET utf8 COLLATE utf8_bin ,
`Interest in Exercise Aerobic in Household` varchar(3) CHARACTER SET utf8 COLLATE utf8_bin ,
`Interest in SpectatorSports Auto Racing in Household` varchar(3) CHARACTER SET utf8 COLLATE utf8_bin ,
`Interest in SpectatorSports on TV in Household` varchar(3) CHARACTER SET utf8 COLLATE utf8_bin ,
`Interest in SpectatorSports Football in Household` varchar(3) CHARACTER SET utf8 COLLATE utf8_bin ,
`Interest in SpectatorSports Baseball in Household` varchar(3) CHARACTER SET utf8 COLLATE utf8_bin ,
`Interest in SpectatorSports Basketball in Household` varchar(3) CHARACTER SET utf8 COLLATE utf8_bin ,
`Interest in SpectatorSports Hockey in Household` varchar(3) CHARACTER SET utf8 COLLATE utf8_bin ,
`Interest in SpectatorSports Soccer in Household` varchar(3) CHARACTER SET utf8 COLLATE utf8_bin ,
`Interest in Tennis in Household` varchar(3) CHARACTER SET utf8 COLLATE utf8_bin ,
`Interest in Golf in Household` varchar(3) CHARACTER SET utf8 COLLATE utf8_bin ,
`Interest in Snow Skiing in Household` varchar(3) CHARACTER SET utf8 COLLATE utf8_bin ,
`Interest in Motorcycling in Household` varchar(3) CHARACTER SET utf8 COLLATE utf8_bin ,
`Interest in Nascar in Household` varchar(3) CHARACTER SET utf8 COLLATE utf8_bin ,
`Interest in Boating Sailing in Household` varchar(3) CHARACTER SET utf8 COLLATE utf8_bin ,
`Interest in Scuba Diving in Household` varchar(3) CHARACTER SET utf8 COLLATE utf8_bin ,
`Interest in Sports Leisure in Household` varchar(3) CHARACTER SET utf8 COLLATE utf8_bin ,
`Interest in Hunting in Household` varchar(3) CHARACTER SET utf8 COLLATE utf8_bin ,
`Interest in Fishing in Household` varchar(3) CHARACTER SET utf8 COLLATE utf8_bin ,
`Interest in Camping Hiking in Household` varchar(3) CHARACTER SET utf8 COLLATE utf8_bin ,
`Interest in Shooting in Household` varchar(3) CHARACTER SET utf8 COLLATE utf8_bin ,
`Interest in Automotive Parts Accessories in Household` varchar(3) CHARACTER SET utf8 COLLATE utf8_bin ,
`FECDonors_NumberOfDonations` varchar(3) CHARACTER SET utf8 COLLATE utf8_bin ,
`FECDonors_TotalDonationsAmount` varchar(5) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL,
`FECDonors_TotalDonationsAmt_Range` varchar(15) CHARACTER SET utf8 COLLATE utf8_bin ,
`FECDonors_LastDonationDate` date ,
`FECDonors_AvgDonation` varchar(5) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL,
`FECDonors_AvgDonation_Range` varchar(15) CHARACTER SET utf8 COLLATE utf8_bin ,
`CensusBlockGroup` varchar(1) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL,
`CensusTract` varchar(6) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL,
`CensusBlock` varchar(4) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL,
`early_voting_returned_ballots_primary_2020_ballotstatus_nyc` varchar(15) CHARACTER SET utf8 COLLATE utf8_bin ,
`Voters_FirstName_c` varchar(23) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL,
`Voters_LastName_c` varchar(27) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL,
`Residence_Addresses_AddressLine_c` varchar(32) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL,
`Residence_Addresses_City_c` varchar(16) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL,
`Residence_Addresses_State_c` varchar(2) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL,
`Zip_c` varchar(5) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL,
`Email Address` varchar(45) CHARACTER SET utf8 COLLATE utf8_bin ,
`Match Type` varchar(3) CHARACTER SET utf8 COLLATE utf8_bin 
) ;


LOAD DATA INFILE '/config/working/Merged3.csv' 
INTO TABLE voterdatareach 
FIELDS TERMINATED BY ',' 
ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 ROWS
(`LALVOTERID` ,	`Voters_StateVoterID` ,	`Voters_CountyVoterID` ,	`Walking_List_Sequence` ,	`HH Code` ,	`VoterTelephones_FullPhone` ,	`VoterTelephones_TelConfidenceCode` ,	`VoterTelephones_TelCellFlag` ,	`View_Ops_CellPhone_FullPhone` ,	`Voters_FirstName` ,	`Voters_MiddleName` ,	`Voters_LastName` ,	`Voters Name Suffix` ,	`Residence_Addresses_AddressLine` ,	`Residence_Addresses_City` ,	`Residence_Addresses_State` ,	`Zip` ,	`Residence_Addresses_HouseNumber` ,	`Residence_Addresses_StreetName` ,	`Residence_Addresses_Designator` ,	`Residence_Addresses_SuffixDirection` ,	`Residence_Addresses_ApartmentNum` ,	`Residence_Addresses_CensusTract` ,	`Residence_Addresses_CensusBlockGroup` ,	`Residence_Addresses_CensusBlock` ,	`Latitude` ,	`Longitude` ,	`Residence_Addresses_ZipPlus4` ,	`Residence_Addresses_City_b` ,	`Residence_Addresses_State_b` ,	`Zip_b` ,	@var1,	@var2,	`Voters_Age` ,	`Ethnic_Description` ,	`Broad Ethnic Groupings` ,	`Mailing_Addresses_AddressLine` ,	`Mailing_Addresses_ExtraAddressLine` ,	`Mailing_Addresses_City` ,	`Mailing_Addresses_State` ,	`Mailing_Addresses_Zip` ,	`Household Primary Language` ,	`Hispanic Country Origin` ,	`Cable or Dish Television` ,	`Religions_Description` ,	`AbsenteeTypes_Description` ,	`VoterParties_Change_Changed_Party` ,	`Voters_VotingPerformanceEvenYearGeneral` ,	`Voters_VotingPerformanceEvenYearPrimary` ,	`Voters_VotingPerformanceEvenYearGeneralAndPrimary` ,	`Voters_VotingPerformanceMinorElection` ,	`AddressDistricts_Change_Changed_County` ,	`AddressDistricts_Change_Changed_CD` ,	`AddressDistricts_Change_Changed_SD` ,	`AddressDistricts_Change_Changed_HD` ,	`Voters_Gender` ,	`MilitaryStatus_Description` ,	`MaritalStatus_Description` ,	`Residence_Families_HHCount` ,	`Residence_HHParties_Description` ,	`Residence_HHGender_Description` ,	`Congressional_District` ,	`State_Senate_District` ,	`State_House_District` ,	`Precinct` ,	`Vote_Frequency` ,	`PRI_BLT_2008-02-05` ,	`PRI_BLT_2008-09-09` ,	`PRI_BLT_2009-09-15` ,	`PRI_BLT_2010-09-14` ,	`PRI_BLT_2011-09-13` ,	`PRI_BLT_2012-04-24` ,	`PRI_BLT_2012-06-26` ,	`PRI_BLT_2012-09-13` ,	`PRI_BLT_2013-09-10` ,	`PRI_BLT_2014-06-24` ,	`PRI_BLT_2014-09-09` ,	`PRI_BLT_2015-09-10` ,	`PRI_BLT_2016-04-19` ,	`PRI_BLT_2016-06-28` ,	`PRI_BLT_2016-09-13` ,	`PRI_BLT_2017-09-12` ,	`PRI_BLT_2018-06-26` ,	`PRI_BLT_2018-09-13` ,	`PRI_BLT_2019-06-25` ,	`PRI_BLT_2020-06-23` ,	`General_1985-11-05` ,	`General_1986-11-04` ,	`General_1987-11-03` ,	`General_1988-11-08` ,	`General_1989-11-07` ,	`General_1990-11-06` ,	`General_1991-11-05` ,	`General_1992-11-03` ,	`General_1993-11-02` ,	`General_1994-11-08` ,	`General_1995-11-07` ,	`General_1996-11-05` ,	`General_1997-11-04` ,	`General_1998-11-03` ,	`General_1999-11-02` ,	`General_2000-11-07` ,	`General_2001-11-06` ,	`General_2002-11-05` ,	`General_2003-11-04` ,	`General_2004-11-02` ,	`General_2005-11-08` ,	`General_2006-11-07` ,	`General_2007-11-06` ,	`General_2008-11-04` ,	`General_2009-11-03` ,	`General_2010-11-02` ,	`General_2011-11-08` ,	`General_2012-11-06` ,	`General_2013-11-05` ,	`General_2014-11-04` ,	`General_2015-11-03` ,	`General_2016-11-08` ,	`General_2017-11-07` ,	`General_2018-11-06` ,	`General_2019-11-05` ,	`Presidential_Primary_1992-04-07` ,	`Presidential_Primary_1996-03-07` ,	`Presidential_Primary_2000-03-07` ,	`Presidential_Primary_2004-03-02` ,	`Presidential_Primary_2008-02-05` ,	`Presidential_Primary_2012-04-24` ,	`Presidential_Primary_2016-04-19` ,	`Presidential_Primary_2020-06-23` ,	`Special_2019-02-26` ,	`Runoff_2001-10-11` ,	`Runoff_2009-09-29` ,	`Runoff_2013-10-01` ,	`PresenceOfChildrenCode` ,	`ISPSA` ,	`Home Purchase Price` ,	`Land Value` ,	`Home Owner/Renter` ,	`Property Type` ,	`DwellingType` ,	@var3,	`EstHomeValue` ,	`MedianEducationYears` ,	`Net Worth` ,	`Investor` ,	`Likely Union Member` ,	`Business Owner` ,	`EstimatedIncomeAmount` ,	`EstimatedIncome` ,	`Education` ,	`OccupationIndustry` ,	`Occupation` ,	`ReligiousContributorInHome` ,	`PoliticalContributerInHome` ,	`DonatesEnvironmentCauseInHome` ,	`DonatesToCharityInHome` ,	`Donates to Animal Welfare` ,	`Donates to Arts and Culture` ,	`Donates to Childrens Causes` ,	`Donates to Healthcare` ,	`Donates to International Aid Causes` ,	`Donates to Veterans Causes` ,	`Donates to Wildlife Preservation` ,	`Donates to Conservative Causes` ,	`Donates to Liberal Causes` ,	`Donates to Local Community` ,	`StateIncomeDecile` ,	`PcntHHWithChildren` ,	`PcntHHSpanishSpeaking` ,	`MosaicZ4` ,	`Horse Owner` ,	`Cat Owner` ,	`Dog Owner` ,	`Other Pet Owner` ,	`Home Office` ,	`Book Buyer In Home` ,	`Family Magazine In Home` ,	`Female Oriented Magazine In Home` ,	`Religious Magazine In Home` ,	`Gardening Magazine In Home` ,	`Culinary Interest Magazine In Home` ,	`Health Fitness Magazine In Home` ,	`Do It Yourselfer Magazine In Home` ,	`Financial Magazine In Home` ,	`Computer Owner In Home` ,	`Household Composition` ,	`Languages` ,	`Dwelling Unit Size` ,	`Upscale Buyer In Home` ,	`Upscale Male Buyer In Home` ,	`Upscale Female Buyer In Home` ,	`Buyer of Antiques in Household` ,	`Buyer of Art in Household` ,	`General Collector in Household` ,	`Stamps Collector in Household` ,	`Coins Collector in Household` ,	`Arts Collector in Household` ,	`Antiques Collector in Household` ,	`Avid Collector in Household` ,	`Sports Collector in Household` ,	`Military Collector in Household` ,	`Interest in Current Affairs Politics In Household` ,	`General Reading in Household` ,	`Religious Reading in Household` ,	`Fiction Science Reading in Household` ,	`Magazines Reading in Household` ,	`Books Audio Reading in Household` ,	`Gun Owner` ,	`Veteran` ,	`Interest in History Military in Household` ,	`Interest in Religious Inspirational in Household` ,	`Interest in Science Space in Household` ,	`Interest in Education Online in Household` ,	`Interest in Electronic Gaming in Household` ,	`Interest in Theater Performing Arts in Household` ,	`Interest in the Arts in Household` ,	`Interest in Musical Instruments in Household` ,	`Interest in Home Repair in Household` ,	`Interest in Auto Work in Household` ,	`Interest in Sewing Knitting in Household` ,	`Interest in Woodworking in Household` ,	`Interest in Photography in Household` ,	`Interest in Aviation in Household` ,	`Interest in House Plants in Household` ,	`Interest in Crafts in Household` ,	`Interest in Gardening in Household` ,	`Interest in Photography Video in Household` ,	`Interest in Smoking in Household` ,	`Interest in Home Furnishings in Household` ,	`Interest in Home Improvement in Household` ,	`Interest in Food Wines in Household` ,	`Interest in Cooking General in Household` ,	`Interest in Cooking Gourmet in Household` ,	`Interest in Foods Natural in Household` ,	`Interest in BoardGames Puzzles in Household` ,	`Interest in Gaming Casino in Household` ,	`Interest in Sweepstakes Contests in Household` ,	`Interest in Travel Domestic in Household` ,	`Interest in Travel International in Household` ,	`Interest in Travel Cruise in Household` ,	`Interest in Exercise Health in Household` ,	`Interest in Exercise Running Jogging in Household` ,	`Interest in Exercise Walking in Household` ,	`Interest in Exercise Aerobic in Household` ,	`Interest in SpectatorSports Auto Racing in Household` ,	`Interest in SpectatorSports on TV in Household` ,	`Interest in SpectatorSports Football in Household` ,	`Interest in SpectatorSports Baseball in Household` ,	`Interest in SpectatorSports Basketball in Household` ,	`Interest in SpectatorSports Hockey in Household` ,	`Interest in SpectatorSports Soccer in Household` ,	`Interest in Tennis in Household` ,	`Interest in Golf in Household` ,	`Interest in Snow Skiing in Household` ,	`Interest in Motorcycling in Household` ,	`Interest in Nascar in Household` ,	`Interest in Boating Sailing in Household` ,	`Interest in Scuba Diving in Household` ,	`Interest in Sports Leisure in Household` ,	`Interest in Hunting in Household` ,	`Interest in Fishing in Household` ,	`Interest in Camping Hiking in Household` ,	`Interest in Shooting in Household` ,	`Interest in Automotive Parts Accessories in Household` ,	`FECDonors_NumberOfDonations` ,	`FECDonors_TotalDonationsAmount` ,	`FECDonors_TotalDonationsAmt_Range` ,	@var4,	`FECDonors_AvgDonation` ,	`FECDonors_AvgDonation_Range` ,	`CensusBlockGroup` ,	`CensusTract` ,	`CensusBlock` ,	`early_voting_returned_ballots_primary_2020_ballotstatus_nyc` ,	`Voters_FirstName_c` ,	`Voters_LastName_c` ,	`Residence_Addresses_AddressLine_c` ,	`Residence_Addresses_City_c` ,	`Residence_Addresses_State_c` ,	`Zip_c` ,	`Email Address` ,	`Match Type` )
; /*SET 
	Voters_BirthDate = STR_TO_DATE(@var1, '%m/%d/%Y') 
	Voters_OfficialRegDate = STR_TO_DATE(@var2, '%m/%d/%Y'),
	HomePurchaseDate  = STR_TO_DATE(@var3, '%m/%d/%Y'),
	FECDonors_LastDonationDate = STR_TO_DATE(@var4, '%m/%d/%Y')
;*/



ALTER TABLE voterdatareach ADD COLUMN voter_id VARCHAR(15) FIRST;
UPDATE voterdatareach SET voter_id = RIGHT(voters_countyvoterID, length(voters_countyvoterID) - 3) where LEFT(voters_countyvoterID, 3) = '081';
UPDATE voterdatareach SET voter_id = RIGHT(voters_countyvoterID, length(voters_countyvoterID) - 2) where LEFT(voters_countyvoterID, 2) = '81' AND voter_id IS null;
CREATE INDEX voterdata_derivedid ON voterdatareach (voter_id);

SELECT COUNT(*) FROM voters WHERE id not IN (SELECT voter_id FROM voterdatareach);
